name: Automatic Record Finder

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger the workflow manually'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install axios

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: node checkYoutubeUploads.js
