name: Automatic Record Finder

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger the workflow manually'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node checkYoutubeUploads.js
